config/routes.rb
Rails.application.routes.draw do
  resources :homes
  devise_for :users

  resources :mangas do
    resources :review_mangas, except: [:show, :index]
  end
  resources :animes do
    resources :review_animes, except: [:show, :index]
  end
  resources :books do
    resources :review_books, except: [:show, :index]
  end
  resources :games do
    resources :review_games, except: [:show, :index]
  end
  resources :movies do
    resources :reviews, except: [:show, :index]
  end
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_one_attached :image
  has_many :review_animes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  has_many :review_books
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :image
  has_many :review_games
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/manga.rb
class Manga < ApplicationRecord
  has_one_attached :image
  has_many :review_mangas
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :image
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/review_anime.rb
class ReviewAnime < ApplicationRecord
  belongs_to :user
  belongs_to :anime
end

app/models/review_book.rb
class ReviewBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review_game.rb
class ReviewGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/review_manga.rb
class ReviewManga < ApplicationRecord
  belongs_to :user
  belongs_to :manga
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :review_animes, dependent: :destroy
  has_many :review_books, dependent: :destroy
  has_many :review_games, dependent: :destroy
  has_many :review_mangas, dependent: :destroy
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @review_games = ReviewGame.where(game_id: @game.id).order("created_at DESC")
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Jogo criado com sucesso.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Jogo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Jogo deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :description, :rating, :developer, :genre, :publisher, :release_date, :platform, :image)
    end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/review_books_helper.rb
module ReviewBooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :título %><br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :descrição %><br>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :desenvolvedora %><br>
    <%= form.text_field :developer %>
  </div>

  <div class="field">
    <%= form.label raw("Gênero(s)") %><br>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :publisher %><br>
    <%= form.text_field :publisher %>
  </div>

  <div class="field">
    <%= form.label :data_de_lançamento %><br>
    <%= form.text_field :release_date %>
  </div>

  <div class="field">
    <%= form.label raw("Plataforma(s)") %><br>
    <%= form.text_field :platform %>
  </div>

  <div class="field">
    <%= form.label :classificação %><br>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :imagem %><br>
    <%= form.file_field :image, required: true %>
  </div>

  <div class="actions">
    <%= form.submit raw("Criar/Atualizar Jogo") %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editando Jogo</h1>

<%= render 'form', game: @game %>

<%= link_to 'Voltar', games_path %>

app/views/games/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Review dos seus jogos favoritos</h1>
    <p>Crie uma conta para compartilhar seus pensamentos sobre suas obras favoritas!</p>
    <p><%= link_to "Inscreva-se", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <% @games.each do |game| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag game.image, style: 'height:400px', class: 'image'), game %>
      </div>
    </div>
  <% end %>
</div>

app/views/games/new.html.erb
<h1>Novo Jogo</h1>

<%= render 'form', game: @game %>

<%= link_to 'Voltar', games_path %>

app/views/games/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <div style="width:450px;height:650px">
          <%= image_tag(@game.image, style:'width:100%;height:100%') %>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th style="width: 25%"></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Título:</strong></td>
                <td><%= @game.title %></td>
              </tr>
              <tr>
                <td><strong>Descrição:</strong></td>
                <td><%= @game.description %></td>
              </tr>
              <tr>
                <td><strong>Gênero(s):</strong></td>
                <td><%= @game.genre %></td>
              </tr>
              <tr>
                <td><strong>Desenvolvedora:</strong></td>
                <td><%= @game.developer %></td>
              </tr>
              <tr>
                <td><strong>Gênero(s):</strong></td>
                <td><%= @game.genre %></td>
              </tr>
              <tr>
                <td><strong>Publisher:</strong></td>
                <td><%= @game.publisher %></td>
              </tr>
              <tr>
                <td><strong>Classificação:</strong></td>
                <td><%= @game.rating %></td>
              </tr>
              <tr>
                <td><strong>Data de lançamento:</strong></td>
                <td><%= @game.release_date %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Escrever uma análise", new_game_review_game_path(@game) %>
        </div>
      </div>
    </div>
    <div class="row-md-offset-3">
      <div><h3>Análises</h3></div>
      <% if @review_games.blank? %>
        <h3>Sem análises</h3>
        <%= link_to "Escrever análise", new_game_review_game_path(@game), class: "btn btn-danger" %>
      <% else %>
        <% @review_games.each do |review_game| %>
          <div class="reviews">
            <small class="author">Análise feita por: <%= review_game.user.name %></small></p>
            <p>Nota: <%= review_game.rating %></p>
            <p><%= review_game.comment %></p>
            <% if user_signed_in?%>
              <% if current_user.admin? -%>
                <% if review_game.user == current_user %>
                  <div class="btn-group">
                    <%= link_to 'Editar', edit_game_review_game_path(@game, review_game.id), class: "btn btn-default" %>
                    <%= link_to 'Deletar', game_review_game_path(@game, review_game.id), data: {:confirm => "Tem certeza?"}, :method => :delete, class: "btn btn-default" %>
                  </div>
                <% else %>
                  <div class="btn-group">
                    <%= link_to 'Deletar', game_review_game_path(@game, review_game.id), data: {:confirm => "Tem certeza?"}, :method => :delete, class: "btn btn-default" %>
                  </div>
                <% end %>
              <% elsif review_game.user == current_user -%>
  	           <div class="btn-group">
  		             <%= link_to 'Editar', edit_game_review_game_path(@game, review_game.id), class: "btn btn-default" %>
                   <%= link_to 'Deletar', game_review_game_path(@game, review_game.id), data: {:confirm => "Tem certeza?"}, :method => :delete, class: "btn btn-default" %>
  	           </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<%if user_signed_in? %>
  <% if current_user.admin? %>
    <%= link_to 'Editar', edit_game_path(@game), class: "btn btn-default" %> |
    <%= link_to 'Voltar', games_path, class: "btn btn-default" %> |
    <%= link_to 'Deletar', game_path(@game), data: {:confirm => "Tem certeza?"}, :method => :delete, class: "btn btn-default" %>
  <% else %>
    <%= link_to 'Voltar', games_path, class: "btn btn-default" %>
  <% end %>
<% else %>
  <%= link_to 'Voltar', games_path, class: "btn btn-default" %>
<% end %>