config/routes.rb
Rails.application.routes.draw do
  resources :homes
  devise_for :users

  resources :mangas do
    resources :review_mangas, except: [:show, :index]
  end
  resources :animes do
    resources :review_animes, except: [:show, :index]
  end
  resources :books do
    resources :review_books, except: [:show, :index]
  end
  resources :games do
    resources :review_games, except: [:show, :index]
  end
  resources :movies do
    resources :reviews, except: [:show, :index]
  end
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_one_attached :image
  has_many :review_animes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  has_many :review_books
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :image
  has_many :review_games
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/manga.rb
class Manga < ApplicationRecord
  has_one_attached :image
  has_many :review_mangas
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :image
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/review_anime.rb
class ReviewAnime < ApplicationRecord
  belongs_to :user
  belongs_to :anime
end

app/models/review_book.rb
class ReviewBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review_game.rb
class ReviewGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/review_manga.rb
class ReviewManga < ApplicationRecord
  belongs_to :user
  belongs_to :manga
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :review_animes, dependent: :destroy
  has_many :review_books, dependent: :destroy
  has_many :review_games, dependent: :destroy
  has_many :review_mangas, dependent: :destroy
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /animes
  # GET /animes.json
  def index
    @animes = Anime.all
  end

  # GET /animes/1
  # GET /animes/1.json
  def show
    @review_animes = ReviewAnime.where(anime_id: @anime.id).order("created_at DESC")
  end

  # GET /animes/new
  def new
    @anime = Anime.new
  end

  # GET /animes/1/edit
  def edit
  end

  # POST /animes
  # POST /animes.json
  def create
    @anime = Anime.new(anime_params)

    respond_to do |format|
      if @anime.save
        format.html { redirect_to @anime, notice: 'Anime criado com sucesso.' }
        format.json { render :show, status: :created, location: @anime }
      else
        format.html { render :new }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animes/1
  # PATCH/PUT /animes/1.json
  def update
    respond_to do |format|
      if @anime.update(anime_params)
        format.html { redirect_to @anime, notice: 'Anime editado com sucesso.' }
        format.json { render :show, status: :ok, location: @anime }
      else
        format.html { render :edit }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animes/1
  # DELETE /animes/1.json
  def destroy
    @anime.destroy
    respond_to do |format|
      format.html { redirect_to animes_url, notice: 'Anime deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anime
      @anime = Anime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anime_params
      params.require(:anime).permit(:title, :synopsis, :rating, :genre, :prequel, :sequel, :image, :release_date)
    end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/review_books_helper.rb
module ReviewBooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/animes/_form.html.erb
<%= form_with(model: anime, local: true) do |form| %>
  <% if anime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

      <ul>
      <% anime.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :título %><br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :sinopse %><br>
    <%= form.text_area :synopsis %>
  </div>

  <div class="field">
    <%= form.label raw("Gênero(s)") %><br>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :anterior %><br>
    <%= form.text_field :prequel %>
  </div>

  <div class="field">
    <%= form.label :seguinte %><br>
    <%= form.text_field :sequel %>
  </div>

  <div class="field">
    <%= form.label :classificação %><br>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :data_de_lançamento %><br>
    <%= form.text_field :release_date %>
  </div>

  <div class="field">
    <%= form.label :imagem %><br>
    <%= form.file_field :image, required: true %>
  </div>

  <div class="actions">
    <%= form.submit raw("Criar/Atualizar Anime") %>
  </div>
<% end %>

app/views/animes/edit.html.erb
<h1>Editando Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Voltar', animes_path %>

app/views/animes/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Review dos seus animes favoritos</h1>
    <p>Crie uma conta para compartilhar seus pensamentos sobre suas obras favoritas!</p>
    <p><%= link_to "Inscreva-se", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <% @animes.each do |anime| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag anime.image, style: 'height:400px', class: 'image'), anime %>
      </div>
    </div>
  <% end %>
</div>

app/views/animes/new.html.erb
<h1>Novo Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Voltar', animes_path %>

app/views/animes/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <div style="width:450px;height:650px">
          <%= image_tag(@anime.image, style:'width:100%;height:100%') %>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th style="width: 25%"></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Título:</strong></td>
                <td><%= @anime.title %></td>
              </tr>
              <tr>
                <td><strong>Sinopse:</strong></td>
                <td><%= @anime.synopsis %></td>
              </tr>
              <tr>
                <td><strong>Gênero(s):</strong></td>
                <td><%= @anime.genre %></td>
              </tr>
              <tr>
                <td><strong>Seguinte:</strong></td>
                <td><%= @anime.sequel %></td>
              </tr>
              <tr>
                <td><strong>Anterior:</strong></td>
                <td><%= @anime.prequel %></td>
              </tr>
              <tr>
                <td><strong>Classificação:</strong></td>
                <td><%= @anime.rating %></td>
              </tr>
              <tr>
                <td><strong>Data de lançamento:</strong></td>
                <td><%= @anime.release_date %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Escrever uma análise", new_anime_review_anime_path(@anime) %>
        </div>
      </div>
    </div>
    <div class="row-md-offset-3">
      <div><h3>Análises</h3></div>
      <% if @review_animes.blank? %>
        <h3>Sem análises</h3>
        <%= link_to "Escrever análise", new_anime_review_anime_path(@anime), class: "btn btn-danger" %>
      <% else %>
        <% @review_animes.each do |review_anime| %>
          <div class="reviews">
            <small class="author">Análise feita por: <%= review_anime.user.name %></small></p>
            <p>Nota: <%= review_anime.rating %></p>
            <p><%= review_anime.comment %></p>
            <% if user_signed_in?%>
              <% if current_user.admin? -%>
                <% if review_anime.user == current_user %>
                  <div class="btn-group">
                    <%= link_to 'Editar', edit_anime_review_anime_path(@anime, review_anime.id), class: "btn btn-default" %>
                    <%= link_to 'Deletar', anime_review_anime_path(@anime, review_anime.id), data: {:confirm => "Tem certeza?"}, :method => :delete, class: "btn btn-default" %>
                  </div>
                <% else %>
                  <div class="btn-group">
                    <%= link_to 'Deletar', anime_review_anime_path(@anime, review_anime.id), data: {:confirm => "Tem certeza?"}, :method => :delete, class: "btn btn-default" %>
                  </div>
                <% end %>
              <% elsif review_anime.user == current_user -%>
  	           <div class="btn-group">
  		             <%= link_to 'Editar', edit_anime_review_anime_path(@anime, review_anime.id), class: "btn btn-default" %>
                   <%= link_to 'Deletar', anime_review_anime_path(@anime, review_anime.id), data: {:confirm => "Tem certeza?"}, :method => :delete, class: "btn btn-default" %>
  	           </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<%if user_signed_in? %>
  <% if current_user.admin? %>
    <%= link_to 'Editar', edit_anime_path(@anime), class: "btn btn-default"  %> |
    <%= link_to 'Voltar', animes_path, class: "btn btn-default" %> |
    <%= link_to 'Deletar', anime_path(@anime), data: {:confirm => "Tem certeza?"}, :method => :delete, class: "btn btn-default" %>
  <% else %>
    <%= link_to 'Voltar', animes_path, class: "btn btn-default" %>
  <% end %>
<% else %>
  <%= link_to 'Voltar', animes_path, class: "btn btn-default" %>
<% end %>