config/routes.rb
Rails.application.routes.draw do
  resources :homes
  devise_for :users

  resources :mangas do
    resources :review_mangas, except: [:show, :index]
  end
  resources :animes do
    resources :review_animes, except: [:show, :index]
  end
  resources :books do
    resources :review_books, except: [:show, :index]
  end
  resources :games do
    resources :review_games, except: [:show, :index]
  end
  resources :movies do
    resources :reviews, except: [:show, :index]
  end
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_one_attached :image
  has_many :review_animes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  has_many :review_books
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :image
  has_many :review_games
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/manga.rb
class Manga < ApplicationRecord
  has_one_attached :image
  has_many :review_mangas
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :image
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/review_anime.rb
class ReviewAnime < ApplicationRecord
  belongs_to :user
  belongs_to :anime
end

app/models/review_book.rb
class ReviewBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review_game.rb
class ReviewGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/review_manga.rb
class ReviewManga < ApplicationRecord
  belongs_to :user
  belongs_to :manga
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :review_animes, dependent: :destroy
  has_many :review_books, dependent: :destroy
  has_many :review_games, dependent: :destroy
  has_many :review_mangas, dependent: :destroy
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Reviewrama", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
          <li><%= link_to "Animes", animes_path %><%= link_to "Novo", new_anime_path, class: "active"%></li>
          <li><%= link_to "Livros", books_path %><%= link_to "Novo", new_book_path, class: "active"%></li>
          <li><%= link_to "Jogos", games_path %><%= link_to "Novo", new_game_path, class: "active"%></li>
          <li><%= link_to "Mangás", mangas_path %><%= link_to "Novo", new_manga_path, class: "active"%></li>
          <li><%= link_to "Filmes", movies_path %><%= link_to "Novo", new_movie_path, class: "active"%></li>
          <li><%= link_to "Conta", edit_user_registration_path %></li>
          <li><%= link_to 'Sair', destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li><%= link_to "Animes", animes_path %></li>
          <li><%= link_to "Livros", books_path %></li>
          <li><%= link_to "Jogos", games_path %></li>
          <li><%= link_to "Mangás", mangas_path %></li>
          <li><%= link_to "Filmes", movies_path %></li>
          <li><%= link_to "Conta", edit_user_registration_path %></li>
          <li><%= link_to 'Sair', destroy_user_session_path, :method => :delete %></li>
          <% end %>
          <%else %>
          <li><%= link_to "Animes", animes_path %></li>
          <li><%= link_to "Livros", books_path %></li>
          <li><%= link_to "Jogos", games_path %></li>
          <li><%= link_to "Mangás", mangas_path %></li>
          <li><%= link_to "Filmes", movies_path %></li>
          <li><%= link_to "Registrar", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Entrar", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>